myproject/models.py
# MODELS.PY
# set up db inside the __init__.py under myproject folder
from myproject import db


class Puppy(db.Model):
    __tablename__ = 'puppies'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    owner = db.relationship('Owner', backref='puppy', uselist=False)

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        if self.owner:
            return f'Puppy name is {self.name} and owner is {self.owner}'
        return f'Puppy name is {self.name} and has no owner yet'


class Owner(db.Model):
    __tablename__ = 'owners'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Text)
    puppy_id = db.Column(db.Integer, db.ForeignKey('puppies.id'))

    def __init__(self, name, puppy_id):
        self.name = name
        self.puppy_id = puppy_id

    def __repr__(self):
        return self.name

myproject/owners/forms.py
# FORMS.PY owners
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):

    name = StringField('Name of the Owner:')
    puppy_id = IntegerField('Id Number of Puppy:')
    submit = SubmitField('Add Owner')

myproject/puppies/forms.py
# FORMS.PY puppies
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField


class AddForm(FlaskForm):
    
    name = StringField('Name of the Puppy:')
    submit = SubmitField('Add Puppy')


class DelForm(FlaskForm):
    
    id = IntegerField('Id Number of Puppy to Remove:')
    submit = SubmitField('Remove Puppy')

myproject/__init__.py
# __init__.py  underneath myproject folder
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False

db = SQLAlchemy(app)
Migrate(app, db)

from myproject.puppies.views import puppies_blueprint
from myproject.owners.views import owners_blueprint

app.register_blueprint(owners_blueprint, url_prefix='/owners')
app.register_blueprint(puppies_blueprint, url_prefix='/puppies')

myproject/owners/views.py
# myproject/owners/views.py
from flask import Blueprint, render_template, redirect, url_for
from myproject import db
from myproject.owners.forms import AddForm
from myproject.models import Owner

owners_blueprint = Blueprint(
    'owners', __name__, template_folder='templates/owners'
)


@owners_blueprint.route('/add', methods=['GET', 'POST'])
def addo():

    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data
        pup_id = form.puppy_id.data

        new_owner = Owner(name, pup_id)
        db.session.add(new_owner)
        db.session.commit()

        return redirect(url_for('puppies.lists'))

    return render_template('addo.html', form=form)

myproject/puppies/views.py
# myproject/puppies/views.py
from flask import Blueprint, render_template, redirect, url_for, flash
from myproject import db
from myproject.puppies.forms import AddForm, DelForm
from myproject.models import Puppy


puppies_blueprint = Blueprint(
    'puppies', __name__, template_folder='templates/puppies'
)


@puppies_blueprint.route('/add', methods=['GET', 'POST'])
def addp():
    form = AddForm()

    if form.validate_on_submit():
        name = form.name.data

        new_pup = Puppy(name)
        db.session.add(new_pup)
        db.session.commit()

        return redirect(url_for('puppies.lists'))

    return render_template('addp.html', form=form)


@puppies_blueprint.route('/list')
def lists():
    puppies = Puppy.query.all()
    return render_template('list.html', puppies=puppies)


@puppies_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():
    form = DelForm()

    if form.validate_on_submit():
        pup_id = form.id.data

        pup = Puppy.query.get(pup_id)
        flash(f'{pup.name} has been adopted, so it\'s no longer in our database')

        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('puppies.delete'))

    return render_template('delete.html', form=form)

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Adopt a puppy - {% block title %} {% endblock %}</title>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">

        <a class="nav-item nav-link" href="{{ url_for('index') }}">Home</a>
        <a class="nav-item nav-link" href="{{ url_for('puppies.addp') }}">Add Pup</a>
        <a class="nav-item nav-link" href="{{ url_for('puppies.lists') }}">List of Pups</a>
        <a class="nav-item nav-link" href="{{ url_for('owners.addo') }}">Add Owner</a>
        <a class="nav-item nav-link" href="{{ url_for('puppies.delete') }}">Delete Pup</a>

    </div>

</nav>
<div class="jumbotron">
{% block content %}
{% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
<footer>

</footer>
</html>

myproject/templates/home.html
{% extends 'base.html' %}
{% block title %} Homepage{% endblock %}
{% block content %}
    <h1>Welcome</h1>
{% endblock %}